---
title: Caja Mágica
date: '2/06/2016 '
---


## Descripción
La Caja Mágica es centro deportivo multiuso construido al lado del parque lineal en el distrito de Usera. La instalación se construyó dentro del proyecto olímpico para Madrid durante el periodo de Gallardón en la alcaldía. 


## Ejercicios
2006, 2007, 2008, 2009


## Distrito
Usera


## Importe
290000000


## Indicios políticos
NA


## Indicios económicos
El gasto ha tenido un sobrecoste superior al 20% de lo presupuestado., El Ayuntamiento tuvo que endeudarse para financiar el gasto.


## Indicios de falta de transparencia y corrupción
La población no fue informada suficientemente del gasto., La información relativa la gasto no es fácilmente accesible al público., Existen vínculos entre el equipo de gobierno que aprobó el gasto y la empresa o empresas adjudicatarias.


## Indicios sociales
El gasto compromete la satisfación de algún derecho básico para alguna parte de la población., El gasto sólo beneficia a una minoría privilegiada de la población., En el barrio o distrito había otras necesidades prioritarias que podrían haberse financiado con el dinero que supuso el gasto.


## Indicios ambientales



## Indicios de género
No hubo evaluación de impacto de género antes de ejecutar el gasto.


## Indicios laborales



## Otros indicios
El proyecto se presupuestó en 140 millones de € pero al final costó cerca de 300.
El mantenimiento supone un coste de 1,35 millones de € al año, por lo que todos los años tiene pérdidas.
Actualmente sólo se usa a nivel profesional para el open de tenis de Madrid y parte de las instalaciones se han subcontratado a la empresa privada Momo Sport Club.
Con el sobrecoste se podrían haber construido en el distrito 5 polideportivos, 5 bibliotecas, 5 escuelas infantiles, 5 centros de mayores y un parque de 30 Ha.

- http://ccaa.elpais.com/ccaa/2015/01/20/madrid/1421790603_306893.html


## Pruebas



## Aspectos a investigar
Contrato con la empresa constructora
Contrato de mantenimiento
Índice uso por los vecinos del distrito 
Contrato de concesión a empresa Momo Sport Club


## Correo
auditausera@gmail.com


