---
title: Contrato de Auxiliares de control Centro Cultural Matadero
date: 10/08/2016
---


## Descripción
Externalización de servicio público


## Ejercicios
2011, 2012, 2013, 2014, 2015, 2016


## Distrito
Arganzuela


## Importe
         NA €


## Indicios políticos
- El gasto no estaba contemplado en el programa electoral.


## Indicios económicos
- Se contrató a una empresa privada para ejecutar el gasto cuando podría haberlo hecho el Ayuntamiento.


## Indicios de falta de transparencia y corrupción
- La población no fue informada suficientemente del gasto.
- La información relativa la gasto no es fácilmente accesible al público.
- Hubo irregularidades en el proceso de contratación.
- Existen vínculos entre el equipo de gobierno que aprobó el gasto y la empresa o empresas adjudicatarias.


## Indicios sociales
- El gasto compromete la satisfación de algún derecho básico para alguna parte de la población.
- El gasto sólo beneficia a una minoría privilegiada de la población.
- En el barrio o distrito había otras necesidades prioritarias que podrían haberse financiado con el dinero que supuso el gasto.


## Indicios ambientales



## Indicios de género
- No hubo evaluación de impacto de género antes de ejecutar el gasto.


## Indicios laborales
- Las condiciones laborales de la empresa que ejecutó el gasto empeoraron tras la adjudicación del contrato del gasto.
- Las condiciones laborales de los trabajadores de la empresa que ejecutó el gasto son sensiblemente peores que la de los trabajadores públicos de la misma categoría.


## Otros indicios
No se cumplen los acuerdos mínimos comprometidos por el Grupo Integra con las trabajadoras, no se cubren las bajas.


## Pruebas



## Aspectos a investigar
Número de personas trabajando, número de horas trabajadas, falta de personal de sustitución y cuando se cubren las bajas se hace por personal en prácticas que no cobran.


