---
title: Mercado de Frutas y Verduras de Legazpi
date: 30/06/2016
---


## Descripción
Abandono del espacio patrimonial del Ayuntamiento y proyecto de Desarrollo Urbanístico


## Ejercicios
2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014


## Distrito
Arganzuela


## Importe
    600.000 €


## Indicios políticos



## Indicios económicos
- El gasto no estaba contemplado en el presupuesto municipal.
- Se contrató a una empresa privada para ejecutar el gasto cuando podría haberlo hecho el Ayuntamiento.


## Indicios de falta de transparencia y corrupción
- La población no fue informada suficientemente del gasto.
- La información relativa la gasto no es fácilmente accesible al público.


## Indicios sociales



## Indicios ambientales



## Indicios de género



## Indicios laborales



## Otros indicios



## Pruebas
El mantenimiento cerrado de la edificación supuso un gasto en seguridad durante una decena de años cerrado.


## Aspectos a investigar
Contrato de seguridad privada.


