---
title: Pago doble del agua por parte de parques y jardines
date: 25/09/2016
---


## Descripción
Al menos dos de las empresas que gestionan el cuidado de parques y jardines, están cobrando por la gestión de agua no potable para el riego, cuando se riegan con agua potable de las bocas de riego que hay en los parques. Pagamos 2 veces


## Ejercicios
2013, 2014, 2015, 2016


## Distrito
Centro, Arganzuela


## Importe
         NA €


## Indicios políticos



## Indicios económicos
- El gasto no estaba contemplado en el presupuesto municipal.


## Indicios de falta de transparencia y corrupción
- La información relativa la gasto no es fácilmente accesible al público.


## Indicios sociales



## Indicios ambientales



## Indicios de género



## Indicios laborales



## Otros indicios



## Pruebas
Tengo una respuesta a una reclamación donde se me indica que el agua de riego no es potable, además de fotos de los camiones usando el agua de las bocas de riego


## Aspectos a investigar
Coste en presupuesto anual en aguas no potables. Hay que revisar a todas las empresas contratadas para ese servicio


