---
title: Puente Monumental Perrault
date: '6/06/2016 '
---


## Descripción
Este puente no constituye en si mismo ningún elemento que pueda considerarse esencial en Madrid Río, además su presupuesto de inversión estaba fijado en 10.126.520 €, sin embargo el coste final según en el anuncio de inauguración en los medios de comunicación fue de 13, 6 millones de euros, esto es una desviación de un 34,4 % por encima de lo presupuestado.


## Ejercicios
2011


## Distrito
Arganzuela


## Importe
13600000


## Indicios políticos
NA


## Indicios económicos
El gasto ha tenido un sobrecoste superior al 20% de lo presupuestado., El Ayuntamiento tuvo que endeudarse para financiar el gasto.


## Indicios de falta de transparencia y corrupción
La población no fue informada suficientemente del gasto., La información relativa la gasto no es fácilmente accesible al público.


## Indicios sociales
El gasto compromete la satisfación de algún derecho básico para alguna parte de la población., En el barrio o distrito había otras necesidades prioritarias que podrían haberse financiado con el dinero que supuso el gasto.


## Indicios ambientales



## Indicios de género



## Indicios laborales



## Otros indicios



## Pruebas
Foto del cartel anunciador de la inversión y los medios de comunicación que recogieron el acto y de inaguración y su coste


## Aspectos a investigar
Porque se realizó esta inversión en la construcción de este puente que no resulta esencial, cuando además era ya patente la gran deuda del Ayuntamiento de Madrid generada por obras de soterramiento de la M-30 y Madrid Río contribuyendo al despilfarro en obras de carácter suntuoso y la desviación que generó respecto de su presupuesto de inversión.


## Correo
antardufe@gmail.com


