---
title: Servicio de guías culturales
date: 18/07/2016
---


## Descripción
este servicio se presta por voluntarios que no cobran del Consistorio


## Ejercicios
2015, 2016


## Distrito
Todo Madrid


## Importe
         NA €


## Indicios políticos



## Indicios económicos



## Indicios de falta de transparencia y corrupción
- La población no fue informada suficientemente del gasto.


## Indicios sociales
- El gasto compromete la satisfación de algún derecho básico para alguna parte de la población.


## Indicios ambientales



## Indicios de género



## Indicios laborales
- Las condiciones laborales de los trabajadores de la empresa que ejecutó el gasto son sensiblemente peores que la de los trabajadores públicos de la misma categoría.


## Otros indicios
Los trabajadores voluntarios que prestan el servicio de guia turístico en la ciudad no cobran por la prestaciópn de este trabajo, según dicen a los usuarios y les reclaman una propina como único medio de pago, ya que alegan que se pagan su inclusión como autónomo y no recben otro estipendio


## Pruebas
el relato de los ciudadanos o turistas que utilizanb que utilizan este servicio "gratuito"


## Aspectos a investigar
es preciso conocer el sistema de funcionamiento de este grupo de contratados para la divulgación cultural e histórica de nuestra ciudad y desde qué fecha se está realizando este tipo de asistencia al turismo, inspeccionando también en calle si suceden solo casos puntuales o es una práctica general.


